### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by ivany4** [mrataj/BBCodeString#1]
Hi. Can you make it universal for iOS and OS X or are there any limitations preventing from doing that?

**Comment by mrataj** [comment]
Just a lack of time :)

If you can do it I would be glad to merge it on the main branch

2015-07-27 13:05 GMT+02:00 Ivan Šinkarenko notifications@github.com:

**Comment by ivany4** [comment]
OK, I'll see if I can help ;)
